language: node_js
node_js:
  - 12
deploy:
  provider: heroku
  buildpack: nodejs
  skip_cleanup: true
  api_key:
    secure: HEROKU_API_KEY
  app: ramoura-pingpong-service
  on:
    all_branches: true