language: node_js
node_js:
- 12
deploy:
  provider: heroku
  buildpack: nodejs
  skip_cleanup: true
  api_key:
    secure: aRVjrE5IX3dX5RJFaxLV++ZjYpiCZGDRIe6eX2YY12a30qfEiq6kA3isGgPN4wAq9k4oPQtiLVDAkiztjZe2ow3V8PK67VBrKGfGteaPZxX0uwoh29XZCkOPtbjqUIeBMl6maKoFfwqlshl9Rs3Y2HP1fMoLhx/ZPeyLQwGHQCN8f5GCES4oz0os5T2fxYt7yC6N1tjZ2rZudsTMz8EyFY6BLRGUzl2PQHwDNxwyGJrihPeq0csiuuyk9mhvkCWzQKDEEU16mRK3i971zREEEewh/gTQsZy8D334vy6hM+Raerg9HQVncPVOpsjGn9I/0B9yRPNHthdiSiswjTnAA1J1QRTgTErXpsH3KLubWNn3SSCcFR8HHM+puj1rBWK84xiw3omzogaHSvslg4vXTolTZlJzRq4CZcXhNVKONfkhzWvTncAZ3r1PPl6lv28usTKnfEK7D1ubeAeyvoz41LKS9mdpy2EviSjMIcUPSJF4AAxalcJUqGPX7jcgGdjdVWJm9j8bxu85HGy8ASzJM+cJm5wV4IxZWC7BPD2UeoNBQ6OMPYxmVgk4QZeQhgqAmANpMI+2G9PTlPsV1xcyrRqpBWHtLZTqQtMXHbBeHRCFSKs7j1N5buXBrhS/YI591en9EYmm78ueLsWxKbK4V9pnoplvK0UG9HmYdd8o0pU=
  app: ramoura-pingpong-service
  on:
    all_branches: true
